service: RescheduleCallFUnction

provider:
  name: aws
  runtime: python3.11
  stage: staging
  region: ap-southeast-1
  iam:
    role: "${ssm:/RescheduleCallFUnction/${sls:stage}/lambda/ROLE}"

# package:
#   individually: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    zip: true

functions:
  RescheduleCallFUnction:
    handler: main.main
    description: Reschedule Call Function
    events:
      - s3:
          bucket: RescheduleCallBucket
          event: s3:ObjectCreated:*

    # package:
    #   patterns:
    #     - "!node_modules/**"
    #     - "!yarn.lock"

    environment:
      KEY: "${ssm:/RescheduleCallFUnction/${sls:stage}/lambda/TABLE_NAME}"
      REGION: "${ssm:/RescheduleCallFUnction/${sls:stage}/lambda/REGION}"
      VALUE: "${ssm:/RescheduleCallFUnction/${sls:stage}/lambda/ROLE}"
